many encoder tests

diff --git a/bin/rstream-transcoder b/bin/rstream-transcoder
--- a/bin/rstream-transcoder
+++ b/bin/rstream-transcoder
@@ -22,11 +22,13 @@ DAEMONTOOLS_SERVICE="/var/service"
 
 VERBOSE=0
 
+HLS_CLEANUP=0
+
 #########################
 #########################
 #########################
 # You should not need to edit anything below this point.
-# If you have/feel the need to do otherwise, please inform me of your changes via github.
+# If you have/f[]eel the need to do otherwise, please inform me of your changes via github.
 #########################
 #########################
 #########################
@@ -73,49 +75,25 @@ genStreamDestinations(){
 	dest_240="$proto://${dest_host}:${dest_port}/${dest_app}/${stream}_240p"
 }
 
-genPlaylistSingle(){
-	if [ -z $1 ] || [ -z $2 ]; then echo "!! invalid stream or bitrate in genPlaylistSingle"; exit 88; fi 
-	playlist=${1}_${2}.m3u8
-	echo ""
-	echo ""
-	echo "*+ generating new ${1}_${2}.m3u8 playlist";
-	echo ""
-	echo ""
-	echo "#EXTM3U" > $playlist
-	echo "#EXT-X-TARGETDURATION:5" >> $playlist
-#	echo "#EXT-X-MEDIA-SEQUENCE:0" >> $playlist
-	echo "#EXT-X-ALLOW-CACHE:0" >> $laylist
-	echo "#EXTINF:5," >> $playlist
-	echo "${1}_${2}00000.ts" >> $playlist
-	echo "${1}_${2}00001.ts" >> $playlist
-	echo "${1}_${2}00002.ts" >> $playlist
-	echo "${1}_${2}00003.ts" >> $playlist
-	echo "${1}_${2}00004.ts" >> $playlist
-	echo "${1}_${2}00005.ts" >> $playlist
-	echo "${1}_${2}00006.ts" >> $playlist
-	echo "${1}_${2}00007.ts" >> $playlist
-	echo "${1}_${2}00008.ts" >> $playlist
-	echo "${1}_${2}00009.ts" >> $playlist
-}
 
 genPlaylistMulti()
 {
-	echo ""
-	echo ""
+	cd $2
 	echo "*+ generating new multi-bitrate ${1}.m3u8 playlist";
-	echo ""
-	echo ""
-	if [ ! -f ${1}_360p.m3u8 ]; then echo "Error, ffmpeg not running ? "; exit 1; fi
+	if [ ! -f ./${1}_360p.m3u8 ]; then echo "Error, ffmpeg not running ? ";
+		echo `pwd`;
+	 exit 1; fi
 	playlist=${1}.m3u8
 	echo "#EXTM3U" > $playlist
-	echo "#EXT-X-1-INF:PROGRAM-ID=1, BANDWIDTH=900000" >> $playlist
-	echo "${1}_72Op.m3u8" >> $playlist
-	echo "#EXT-X-1-INF:PROGRAM-ID=1, BANDWIDTH=700000" >> $playlist
+#	echo "#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=128000" >> $playlist
+#	echo "${1}_240p.m3u8" >> $playlist
+	echo "#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=256000" >> $playlist
+	echo "${1}_360p.m3u8" >> $playlist
+	echo "#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=396000" >> $playlist
 	echo "${1}_480p.m3u8" >> $playlist
-	echo "#EXT-X-1-INF:PROGRAM-ID=1, BANDWIDTH=500000" >> $playlist
-	echo "${1}_360p.m3u8" >> $playlist
-	echo "#EXT-X-1-INF:PROGRAM-ID=1, BANDWIDTH=150000" >> $playlist
-	echo "${1}_360p.m3u8" >> $playlist
+#	echo "#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=512000" >> $playlist
+#	echo "${1}_720p.m3u8" >> $playlist
+	
 }
 
 transcoderNginxHLS(){
@@ -127,24 +105,26 @@ transcoderNginxHLS(){
 	src="rtmp://$NGINX_RTMP_IP:$NGINX_RTMP_PORT/$app/$stream"
 
 	checkDir $HOME/tmp/ffmpeg/hls -c www 777
+
 	cd $HOME/tmp/ffmpeg/hls
-	genPlaylistSingle $stream "720p"
-	genPlaylistSingle $stream "480p"
-	genPlaylistSingle $stream "360p"
-	genPlaylistSingle $stream "240p"
 
-	(sleep 15 && cd $HLS_PATH/hls  && genPlaylistMulti $stream) &
+	if [ ! -z $HLS_CLEANUP ] && [ $HLS_CLEANUP -eq 1 ]; then
+		echo "** Cleaning up HLS files older than 5 minutes"
+		find $HOME/tmp/ffmpeg/hls -mmin +5 -name "*.m3u8" -o -name "*.ts" -o -name "*.core" -exec rm -f {} \;
+	fi
 
-	# Please improve or modify these to your liking !
-#	cmd="$cmd -re -acodec libfaac -ar 44000 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 512k -vpre libx264-ipod640 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list_size 0 -segment_list ${stream}_720p.m3u8 -segment_format mpegts ${stream}_720p%05d.ts"
-	cmd="$cmd -re -acodec libfaac -ar 44000 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 512k -vpre libx264-ipod640 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list_size 10 -segment_wrap 10 -segment_format mpegts ${stream}_720p%05d.ts"
-	cmd="$cmd -re -acodec libfaac -ar 44000 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 512k -vpre libx264-ipod640 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list_size 10 -segment_wrap 10 -segment_format mpegts ${stream}_480p%05d.ts"
-	cmd="$cmd -re -acodec libfaac -ar 44000 -b:a 96k -vcodec libx264 -s 426x250  -b:v 256k -vpre libx264-ipod320 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list_size 10 -segment_wrap 10 -segment_format mpegts ${stream}_360p%05d.ts"
-	cmd="$cmd -re -acodec libfaac -ar 44000 -b:a 48k -vcodec libx264 -s 426x250  -b:v 128k -vpre libx264-ipod320 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list_size 10 -segment_wrap 10 -segment_format mpegts ${stream}_240p%05d.ts"
-	logHeader "Enconding source: $src"
-	logHeader "Encoder destinations: $cmd"
-	exec $FFMPEG_BIN  -loglevel fatal -threads 15 -i "$src live=1" $cmd
+#	if [ -f $HOME/tmp/ffmpeg/hls/lock.${stream} ]; then echo "!! Ffmpeg already running for stream $stream ?"; exit 0; fi
 
+	(sleep 20 && genPlaylistMulti $stream $HOME/tmp/ffmpeg/hls) &
+
+	cmd=""
+	cmd="$cmd -re -c:a libfaac -ar 44000 -b:a 96k -flags -global_header -map 0 -f segment -segment_time 10 -segment_format mpegts ${stream}_720p%05d.ts"
+#	cmd="$cmd -re -c:a libfaac -ar 44000 -b:a 96k -c:v libx264 -preset ultrafast -crf 23 -s 854x480  -b:v 296k -vpre libx264-ipod640 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list ${stream}_480p.m3u8 -segment_list_live 1 -segment_list_size 10 -segment_format mpegts ${stream}_480p%05d.ts"
+#	cmd="$cmd -re -c:a libfaac -ar 22050 -b:a 64k -c:v libx264 -preset ultrafast -crf 23 -s 640x360  -b:v 256k -vpre libx264-ipod320 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list ${stream}_360p.m3u8 -segment_list_live 1 -segment_list_size 10 -segment_format mpegts ${stream}_360p%05d.ts"
+#	cmd="$cmd -re -c:a libfaac -ar 22050 -b:a 48k -c:v libx264 -preset ultrafast -crf 23 -s 426x240  -b:v 128k -vpre libx264-ipod320 -flags -global_header -map 0 -f segment -segment_time 10 -segment_list ${stream}_240p.m3u8 -segment_list_live 1 -segment_list_size 10 -segment_format mpegts ${stream}_240p%05d.ts"
+	logHeader "Running enconding args: $cmd"
+	$FFMPEG_BIN -loglevel info -i "$src buffer=3000 live=1 timeout=500" $cmd
+	sleep 3
 }
 # nginx transcoding - working as of 0.4
 transcoderNginxH264(){
@@ -155,25 +135,37 @@ transcoderNginxH264(){
 	if [ -z $1 ]; then echo "!! error missing stream name, exiting !!"; exit 99; fi
 	stream=$1
 
+	if [ -f $HOME/tmp/nginx/hls/lock.${stream} ]; then echo "Lock found for stream $stream !! exiting"; exit 0; fi
+		touch $HOME/tmp/nginx/hls/lock.${stream}
+
 	src="rtmp://$NGINX_RTMP_IP:$NGINX_RTMP_PORT/$app/$stream"
 	genStreamDestinations "rtmp" $NGINX_RTMP_IP $NGINX_RTMP_PORT $dest_app $stream h264
-
+HLS_CLEANUP=1
 	# if hls is enabled and set to nginx, create the multi-bitrate playlist 10 secs after the stream started to aboid "iOS stuck on black screen"
 	if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ] && [ ! -z $HLS_TYPE ] && [ $HLS_TYPE = "nginx" ]; then
 		checkDir $HOME/tmp/nginx/hls -c www 777;
-		echo "** Cleaning up HLS files older than 5 minutes"
-		find $HOME/tmp/nginx/hls -mmin +5 -name "*.m3u8" -o -name "*.ts" -exec rm -f {} \;
+		if [ ! -z $HLS_CLEANUP ] && [ $HLS_CLEANUP -eq 1 ]; then
+			echo "** Cleaning up HLS files older than 5 minutes"
+			find $HOME/tmp/nginx/hls -mmin +5 -name "${stream}_*.m3u8" -o -name "${stream}_*.ts" -o -name "lock.${stream}" -exec rm -f {} \;
+		fi
 		echo "** Launching multi-bitrate sleeping beauty"
-		(sleep 20 && cd $HLS_PATH/hls && genPlaylistMulti $stream) &
+		(sleep 10 && genPlaylistMulti $stream $HLS_PATH/hls) &
 	fi
-
-	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 896k -r 25 -metadata streamName=${stream}_720p -f flv $dest_720"
-	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 854x480 -b:v 512k -r 25 -metadata streamName=${stream}_480p -f flv $dest_480"
-	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 96k -vcodec libx264 -s 640x360 -b:v 256k -r 25 -metadata streamName=${stream}_360p  -f flv $dest_360"
-	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 48k -vcodec libx264 -s 426x250 -b:v 128k -r 25 -metadata streamName=${stream}_240p  -f flv $dest_240"
-
+	cmd=""
+#	cmd="$cmd -re -c:a libfaac -ar 44100 -b:a 96k -c:v libx264 -preset fast -crf 16 -s 1280x720 -b:v 1024k -r 25 -metadata streamName=${stream}_720p -f flv $dest_720"
+#	cmd="$cmd -re -acodec copy -vcodec copy -metadata streamName=${stream}_720p -r 25 -f flv $dest_720"
+#	cmd="$cmd -re -c:a libfaac -ar 44100 -b:a 96k -c:v libx264 -preset fast -crf 18 -s 854x480 -b:v 512k -r 25 -metadata streamName=${stream}_480p -f flv $dest_480"
+#	cmd="$cmd -re -c:a libfaac -ar 22050 -b:a 64k -c:v libx264 -preset ultrafast -crf 20 -s 640x360 -b:v 396k -r 25 -metadata streamName=${stream}_360p  -f flv $dest_360"
+#	cmd="$cmd -re -c:a libfaac -ar 22050 -b:a 48k -c:v libx264 -preset ultrafast -crf 23  -s 426x240 -b:v 256k -r 25 -metadata streamName=${stream}_240p  -f flv $dest_240"
+	cmd="$cmd -re -acodec copy -vcodec copy -metadata streamName=${stream}_720p -r 25 -f flv $dest_720"
+	cmd="$cmd -re -c:a libfaac -ar 44100 -b:a 96k -c:v libx264 -preset fast -crf 18 -s 800x600 -b:v 512k -r 25 -metadata streamName=${stream}_480p -f flv $dest_480"
+	cmd="$cmd -re -c:a libfaac -ar 22050 -b:a 64k -c:v libx264 -preset ultrafast -crf 20 -s 600x480 -b:v 396k -r 25 -metadata streamName=${stream}_360p  -f flv $dest_360"
+	cmd="$cmd -re -c:a libfaac -ar 22050 -b:a 48k -c:v libx264 -preset ultrafast -crf 23  -s 320x240 -b:v 256k -r 25 -metadata streamName=${stream}_240p  -f flv $dest_240"
 	logHeader "Running enconding args: $cmd"
-	exec $FFMPEG_BIN -loglevel fatal -threads 16  -i "$src live=1" $cmd
+	$FFMPEG_BIN -loglevel fatal -i "$src buffer=100 timeout=2" $cmd
+	rm -f $HOME/tmp/nginx/hls/lock.${stream}
+
+	#exec $FFMPEG_BIN -threads 16  -i "$src live=1" $cmd
 }
 
 transcoderCrtmpd(){
@@ -186,6 +178,7 @@ transcoderCrtmpd(){
 	src="rtmp://$CRTMPD_RTMP_IP:$CRTMPD_RTMP_PORT/$app/$stream"
 
 	genStreamDestinations "tcp" $CRTMPD_LIVEFLV_IP $CRTMPD_LIVEFLV_PORT $stream
+	cmd=""
 	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 896k -f flv -metadata streamName=${stream}_720p -f flv $dest_720"
 	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 854x480 -b:v 512k -f flv -metadata streamName=${stream}_480p -f flv $dest_480"
 	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 96k -vcodec libx264 -s 640x360 -b:v 396k -f flv -metadata streamName=${stream}_360p -f flv $dest_360"
