added a POC as rsync-streaming-0.1 + added several enhancements for transcoding support

diff --git a/bin/rstream-core b/bin/rstream-core
--- a/bin/rstream-core
+++ b/bin/rstream-core
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routeHelp; exit 2; fi
 
 ## Used for log consmetics
 logRoute(){
@@ -101,6 +101,8 @@ routeInit(){
 	checkDir $HOME/shared/www -c $USER 755
 	checkDir $HOME/tmp -c
 	if [ ! -z $NGINX_HLS ] && [ $NGINX_HLS -eq 1 ]; then checkDir $HOME/tmp/hls -c www 777; fi
+	if [ ! -z $FFMPEG_HLS ] && [ $FFMPEG_HLS -eq 1 ]; then checkDir $HOME/tmp/hls/ipad -c www 777; fi
+	if [ ! -z $FFMPEG_HLS ] && [ $FFMPEG_HLS -eq 1 ]; then checkDir $HOME/tmp/hls/iphone -c www 777; fi
 }
 
 routeHelp(){
@@ -111,8 +113,6 @@ routeHelp(){
 
 route(){
 	if [ -z $1 ]; then routeHelp; exit 1; fi
-	. $HOME/etc/rstream.conf
-	routeInit
 	case $1 in
 		stop)
 			nginxRouter "stop"
@@ -122,9 +122,14 @@ route(){
 			killall -TERM readproctitle supervise multilog crtmpserver
 		;;
 		start)
-			daemontoolsRouter "start"
 			nginxRouter "start"
+			daemontoolsRouter "start"
 			crtmpdRouter "start"
+		;;
+		restart)
+			route "stop"
+			sleep 3
+			route "start"
 		;;
 		-link)
 			setupServices
diff --git a/bin/rstream-freebsd9_common-helper b/bin/rstream-freebsd9_common-helper
--- a/bin/rstream-freebsd9_common-helper
+++ b/bin/rstream-freebsd9_common-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
 
 ## Used to check the existence of a given username on the system
 checkUser(){
@@ -66,7 +66,7 @@ fi
 }
 
 ## Used to check if a given portname ($1) is installed on the current system
-checkPort(){
+checkDependency(){
 	if [ ! `pkg_info | grep -q $1 && echo $?` -eq 0 ]; then echo "!! port \"$1\" is not installed on this system ! exiting.": exit 99; fi
 	echo "* found port $1";
 }
diff --git a/bin/rstream-freebsd9_crtmpd-helper b/bin/rstream-freebsd9_crtmpd-helper
--- a/bin/rstream-freebsd9_crtmpd-helper
+++ b/bin/rstream-freebsd9_crtmpd-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
 
 ####
 ### CRTMPD setup
diff --git a/bin/rstream-freebsd9_daemontools-helper b/bin/rstream-freebsd9_daemontools-helper
--- a/bin/rstream-freebsd9_daemontools-helper
+++ b/bin/rstream-freebsd9_daemontools-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; fi
+if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; exit 2; fi
 
 ####
 ### daemontools Setup
@@ -20,7 +20,7 @@ if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file di
 daemontoolsSetup(){
 	logHeader "daemontools setup"
 	# check if daemontools is installed
-	checkPort "daemontools"
+	checkDependency "daemontools"
 	# check if services exist
 	checkDir $DAEMONTOOLS_SERVICE -rc
 	# enable daemontools
diff --git a/bin/rstream-freebsd9_nginx-helper b/bin/rstream-freebsd9_nginx-helper
--- a/bin/rstream-freebsd9_nginx-helper
+++ b/bin/rstream-freebsd9_nginx-helper
@@ -12,7 +12,7 @@
 #
 #######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
 
 ####
 ### Nginx setup
@@ -20,7 +20,7 @@ if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file di
 nginxSetup(){
 	logHeader "nginx setup"
 	# test if nginx is installed
-	checkPort "nginx"
+	checkDependency "nginx"
 	nginx_bin=`which nginx` # should result in /usr/local/bin/nginx
 	# test if nginx was compiled with nginx-rtmp support
 	if [ ! `$nginx_bin -V 2>&1 | grep -q rtmp &&  echo $?` -eq 0 ]; then echo "!! nginx was not compiled with nginx-rtmp support , existing."; exit 99; fi
