pre 0.5

diff --git a/bin/rstream-transcoder b/bin/rstream-transcoder
--- a/bin/rstream-transcoder
+++ b/bin/rstream-transcoder
@@ -54,7 +54,8 @@ transcodeInit(){
 	proto=$1
 	dest_host=$2
 	dest_port=$3
-	stream=$4
+	dest_app=$4
+	stream=$5
 	# a bit of logic ..
 	dest_720="$proto://${dest_host}:${dest_port}/r/${stream}_720p"
 	dest_480="$proto://${dest_host}:${dest_port}/r/${stream}_480p"
@@ -66,16 +67,41 @@ transcodeInit(){
 
 # nginx transcoding - working as of 0.4
 transcoderNginx(){
-	if [ -z $FFMPEG_NGINX_ENABLE ] || [ ! $FFMPEG_NGINX_ENABLE -eq 1 ]; then echo "Error: \"-run nginx\" supplied, but FFMPEG_NGINX_ENABLE is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
+	if [ -z $FFMPEG_NGINX_ENABLE ] || [ ! $FFMPEG_NGINX_ENABLE -eq 1 ]; then echo "Error: \"-run nginx <streamname>\" supplied, but FFMPEG_NGINX_ENABLE is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
 
-	app="r"
+	app="proxy"
+	dest_app="r"
 	if [ -z $1 ]; then echo "!! error missing stream name, exiting !!"; exit 99; fi
 	stream=$1
+
+	if [ ! -z $2 ] && [ $2 = "-link" ]; then
+		echo "*+ generating new ffmpeg/run script";
+		checkDir $HOME/tmp/ffmpeg -c rstream 700
+		checkDir $HOME/var/log/ffmpeg -c rstream 700
+		checkDir $HOME/var/supervise/ffmpeg-nginx-${stream}/log -c rstream 755
+		cat $HOME/include/templates/ffmpeg-run.tpl \
+			| sed s,_HOME_,$HOME,g \
+			| sed s,_USER_,$USER,g \
+			| sed s,_STREAM_,$stream,g \
+			| sed s,_DAEMON_,'nginx',g \
+			> $HOME/var/supervise/ffmpeg-nginx-${stream}/run
+			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/run
+		echo "*+ generating new ffmpeg/run/log script";
+		cat $HOME/include/templates/ffmpeg-run-log.tpl \
+			| sed s,_HOME_,$HOME,g \
+			| sed s,_USER_,$USER,g \
+			> $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
+			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
+			exit 0;
+	fi
+
+
 	src="rtmp://$NGINX_RTMP_IP:$NGINX_RTMP_PORT/$app/$stream"
-	transcodeInit "rtmp" $NGINX_RTMP_IP $NGINX_RTMP_PORT $stream
+	transcodeInit "rtmp" $NGINX_RTMP_IP $NGINX_RTMP_PORT $dest_app $stream
 
 	checkDir $HOME/tmp/nginx/hls -c www 777;
 
+	echo "*+ generating new ${stream}.m3u8 playlist";
 	echo "#EXTM3U" > $HOME/tmp/nginx/hls/${stream}.m3u8
 	echo "#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=860000" >> $HOME/tmp/nginx/hls/${stream}.m3u8
 	echo "${stream}_72Op.m3u8" >> $HOME/tmp/nginx/hls/${stream}.m3u8
@@ -92,33 +118,58 @@ transcoderNginx(){
 	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 96k -vcodec libx264 -s 640x360 -b:v 300k -f flv $dest_360"
 	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 48k -vcodec libx264 -s 426x250 -b:v 100k -f flv $dest_240"
 	echo ""
-	logHeader "Running $ffmpeg_bin -verbosity=1 -threads 15 -i \"$src live=1\"  $cmd"
+	logHeader "Running $ffmpeg_bin -loglevel 1 -verbosity 1 -threads 15 -i \"$src live=1\"  $cmd"
 	echo
 	exec $ffmpeg_bin  -i "$src live=1" $cmd
 }
 
-transcodeCrtmpd(){
-	if [ -z $FFMPEG_CRTMPD_TO_CRTMPD_TRANSCODING ] || [ ! $FFMPEG_CRTMPD_TO_CRTMPD_TRANSCODING -eq 1 ]; then echo "Error: \"-run m1\" supplied, but FFMPEG_CRTMPD_TO_CRTMPD_TRANSCODING is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
+transcoderCrtmpd(){
+	if [ -z $FFMPEG_CRTMPD_ENABLE ] || [ ! $FFMPEG_CRTMPD_ENABLE -eq 1 ]; then echo "Error: \"-run crtmpd <streamname>\" supplied, but FFMPEG_CRTMPD_ENABLE is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
 
 	# hls_iphone="$HOME/etc/ffmpeg-presets/libx264-ipod320.ffpreset"
 	# hls_ipad="$HOME/etc/ffmpeg-presets/libx264-ipod640.ffpreset"
+	if [ -z $1 ]; then echo "!! error missing stream name, exiting !!"; exit 99; fi
+
 	app="proxy"
+	dest_app="r"
 	stream=$1
+
+
+	if [ ! -z $2 ] && [ $2 = "-i" ]; then
+		echo "*+ generating new ffmpeg/run script";
+		checkDir $HOME/tmp/ffmpeg -c rstream 700
+		checkDir $HOME/var/log/ffmpeg -c rstream 700
+		checkDir $HOME/var/supervise/ffmpeg-nginx-${stream}/log -c rstream 755
+		cat $HOME/include/templates/ffmpeg-run.tpl \
+			| sed s,_HOME_,$HOME,g \
+			| sed s,_USER_,$USER,g \
+			| sed s,_STREAM_,$stream,g \
+			| sed s,_DAEMON_,'nginx',g \
+			> $HOME/var/supervise/ffmpeg-nginx-${stream}/run
+			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/run
+		echo "*+ generating new ffmpeg/run/log script";
+		cat $HOME/include/templates/ffmpeg-run-log.tpl \
+			| sed s,_HOME_,$HOME,g \
+			| sed s,_USER_,$USER,g \
+			> $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
+			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
+			exit 0;
+	fi
+
 	src="rtmp://$CRTMPD_RTMP_IP:$CRTMPD_RTMP_PORT/$app/$stream"
 
-	hls_iphone="libx264-ipod320"
-	hls_ipad="libx264-ipod640"
-	FFMPEG_HLS=1
 	transcodeInit "tcp" $CRTMPD_LIVEFLV_IP $CRTMPD_LIVEFLV_PORT $stream
 	#ffmpeg_bin=/home/rstream/bin/ffmpeg
-	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 860k -f flv -metadata streamName=${stream} -f flv $dest_720"
-	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 854x480 -b:v 512k -f flv -metadata streamName=${stream} -f flv $dest_480"
-	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 96k -vcodec libx264 -s 640x360 -b:v 396k -f flv -metadata streamName=${stream} -f flv $dest_360"
-	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 48k -vcodec libx264 -s 426x250 -b:v 256k -f flv -metadata streamName=${stream} -f flv $dest_240"
-	if [ ! -z $FFMPEG_HLS ] && [ $FFMPEG_HLS -eq 1 ]; then
+	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 860k -f flv -metadata streamName=${stream}_720 -f flv $dest_720"
+	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 854x480 -b:v 512k -f flv -metadata streamName=${stream}_480 -f flv $dest_480"
+	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 96k -vcodec libx264 -s 640x360 -b:v 396k -f flv -metadata streamName=${stream}_360 -f flv $dest_360"
+	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 48k -vcodec libx264 -s 426x250 -b:v 256k -f flv -metadata streamName=${stream}_240 -f flv $dest_240"
+	#if [ ! -z $FFMPEG_HLS ] && [ $FFMPEG_HLS -eq 1 ]; then
+	#	hls_iphone="libx264-ipod320"
+	#	hls_ipad="libx264-ipod640"
 	#	cmd=" -re -an -c:v libx264 -b:v 128k  -vpre $hls_iphone -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $HLS_PATH/$app/$stream/${stream}_iphone.m3u8 -segment_format mpegts $HLS_PATH/$app/iphone/stream%05d.ts"
 	#	cmd=" -re -an -c:v libx264 -b:v 256k -vpre $hls_ipad -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $HLS_PATH/$app/$stream/${stream}_ipad.m3u8 -segment_format mpegts $HLS_PATH/ipad/$stream/stream%05d.ts"
-	fi
+	#fi
 	echo ""
 	logHeader "Running $ffmpeg_bin -threads 15 -i \"$src live=1\"  $cmd"
 	echo
@@ -171,8 +222,8 @@ routeTranscoder(){
 		-run)
 			if [ -z $2 ]; then routeHelp; exit 99; fi
 			case $2 in
-				crtmpd) transcoderCrtmpd $3;; # CRTMPD (RTMP / FLV) > ffmpeg > CRTMPD (tcvp / FLV)
-				nginx) transcoderNginx $3;; # CRTMPD (RTMP / FLV) > ffmpeg > NGINX (rtmp / FLV)
+				crtmpd) transcoderCrtmpd $3 $4;; # CRTMPD (RTMP / FLV) > ffmpeg > CRTMPD (tcvp / FLV)
+				nginx) transcoderNginx $3 $4;; # CRTMPD (RTMP / FLV) > ffmpeg > NGINX (rtmp / FLV)
 				*) routeHelp;;
 			esac
 		;;
@@ -180,7 +231,7 @@ routeTranscoder(){
 }
 
 
-routeTranscoder $1 $2 $3
+routeTranscoder $1 $2 $3 $4
 #checkDir $HLS_PATH/$app/$stream -rc
 
 # From https://groups.google.com/forum/#!topic/c-rtmp-server/bzsV61wJGHg[1-25]
diff --git a/include/rstream-config/rstream-config-crtmpd-helper b/include/rstream-config/rstream-config-crtmpd-helper
--- a/include/rstream-config/rstream-config-crtmpd-helper
+++ b/include/rstream-config/rstream-config-crtmpd-helper
@@ -13,10 +13,10 @@
 ######################################################################################
 
 if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ ! -f $CRTMPD_BIN ]; then echo "!! error, crtmpd not found, exiting !!"; exit 99; fi 
 
-logHeader "* entering crtmpd config helper"
+logSection "* entering crtmpd config helper"
 
-CRTMPD_BIN="/usr/local/bin/crtmpserver"
 CRTMPD_RTMP_IP=""
 CRTMPD_RTMP_PORT=""
 CRTMPD_LIVEFLV_IP=""
@@ -24,7 +24,7 @@ CRTMPD_LIVEFLV_PORT=""
 CRTMPD_REGEN_CONF="1"
 
 askCrtmpdBin(){
-	logHeader "General config"
+	logSection "General config"
 	echo -n "Where is your crtmpserver binary ? "
 	read tmp
 	if [ ! -f $tmp ]; then echo "!! cannot find crtmpserver binary in $tmp !!"; askCrtmpdBin;
@@ -33,18 +33,21 @@ askCrtmpdBin(){
 if [ -z $CRTMPD_BIN ]; then askCrtmpdBin; fi
 
 askRTMP(){
-	logHeader "RTMP config"
-	echo -n "What IP address should crtmpd use to listen to incoming and outgoing RTMP connections [x.x.x.x] ? "
+	logSection "RTMP config"
+	
+	echo -n "What IP address should crtmpd use to listen to incoming and outgoing RTMP connections [$HOST_IP] ? "
 	read CRTMPD_RTMP_IP
+	if [ -z $CRTMPD_RTMP_IP ]; then CRTMPD_RTMP_IP=$HOST_IP; fi
 
-	echo -n "What PORT should crtmpd use to listen to incoming and outgoing RTMP connections on $CRTMPD_RTMP_IP [1935] ? "
+	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then port=1936; else port=1935; fi
+	echo -n "What PORT should crtmpd use to listen to incoming and outgoing RTMP connections on $CRTMPD_RTMP_IP [$port] ? "
 	read CRTMPD_RTMP_PORT
-	if [ -z $CRTMPD_RTMP_PORT ]; then CRTMPD_RTMP_PORT=1935; fi
+	if [ -z $CRTMPD_RTMP_PORT ]; then CRTMPD_RTMP_PORT=$port; fi
 
 	echo "** Are these settings correct ?"
 	echo "- crtmpd RTMP IP: $CRTMPD_RTMP_IP"
 	echo "- crtmpd RTMP PORT: $CRTMPD_RTMP_PORT"
-	echo -n "[y/n] "
+	echo -n "[y/N] "
 	read tmp
 	case $tmp in
 		y|Y) echo "* ok";;
@@ -54,25 +57,41 @@ askRTMP(){
 if [ -z $CRTMPD_RTMP_IP ] || [ -z $CRTMPD_RTMP_PORT ]; then askRTMP; fi
 
 askProxyData(){
-	logHeader "PROXY Push config"
+	logSection "PROXY Push config"
 
-	echo -n "To what rtmp://user:pass@host:port/:app should we push the current stream to ? "
+	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then rtmp_host="rtmp://$CRTMPD_RTMP_IP:1935/r"
+	else rtmp_host="rtmp://user:pass@host:port/app"; fi
+	echo -n "To what rtmp address should we push the current stream to [$rtmp_host] ? "
 	read CRTMPD_PROXY_URL
-	if [ -z $CRTMPD_PROXY_URL ]; then askProxyData; fi
+	if [ -z $CRTMPD_PROXY_URL ]; then CRTMPD_PROXY_URL=$rtmp_host; fi
 
-	echo -n "What local stream should we push to $CRTMPD_PROXY_URL [test] ? "
-	read CRTMPD_PROXY_LSTREAM
-	if [ -z $CRTMPD_PROXY_LSTREAM ]; then CRTMPD_PROXY_LSTREAM="test"; fi
+	echo -n "Do you want to enable proxy transparentStream mode ? (implies you patched crtmpd !) ? [y/N] "
+	read CRTMPD_PROXY_TRANSPARENT
+	case $tmp in
+		y|Y) CRTMPD_PROXY_TRANSPARENT=1;;
+		n) CRTMPD_PROXY_TRANSPARENT=0;;
+		*) askProxyData;;
+	esac
 
-	echo -n "As what destination stream name should we push local stream \"$CRTMPD_PROXY_LSTREAM\" to  \"$CRTMPD_PROXY_URL\" [$CRTMPD_PROXY_LSTREAM] ? "
-	read CRTMPD_PROXY_DSTREAM
-	if [ -z $CRTMPD_PROXY_DSTREAM ]; then CRTMPD_PROXY_DSTREAM=$CRTMPD_PROXY_LSTREAM; fi
+	if [ -z $CRTMPD_PROXY_TRANSPARENT ] || [ ! $CRTMPD_PROXY_TRANSPARENT -eq 1 ]; then
+		echo -n "What local stream should we push to $CRTMPD_PROXY_URL [test] ? "
+		read CRTMPD_PROXY_LSTREAM
+		if [ -z $CRTMPD_PROXY_LSTREAM ]; then CRTMPD_PROXY_LSTREAM="test"; fi
+	
+		echo -n "As what destination stream name should we push local stream \"$CRTMPD_PROXY_LSTREAM\" to \"$CRTMPD_PROXY_URL\" [$CRTMPD_PROXY_LSTREAM] ? "
+		read CRTMPD_PROXY_DSTREAM
+		if [ -z $CRTMPD_PROXY_DSTREAM ]; then CRTMPD_PROXY_DSTREAM=$CRTMPD_PROXY_LSTREAM; fi
+	fi
 
 	echo "** Are these settings correct ?"
 	echo "- crtmpd PROXY URL: $CRTMPD_PROXY_URL"
-	echo "- crtmpd PROXY LOCAL STREAM: $CRTMPD_PROXY_LSTREAM"
-	echo "- crtmpd PROXY DESTINATION STREAM: $CRTMPD_PROXY_DSTREAM"
-	echo -n "[y/n] "
+	if [ -z $CRTMPD_TRANSPARENT_STREAM ] || [ ! $CRTMPD_TRANSPARENT_STREAM -eq 1 ]; then
+		echo "- crtmpd PROXY LOCAL STREAM: $CRTMPD_PROXY_LSTREAM"
+		echo "- crtmpd PROXY DESTINATION STREAM: $CRTMPD_PROXY_TRANSPARENT"
+	else
+		echo "- CRTMPD_PROXY_TRANSPARENT is enabled in crtmpd !"
+	fi
+	echo -n "[y/N] "
 	read tmp
 	case $tmp in
 		y|Y) echo "* ok";;
@@ -91,7 +110,7 @@ if [ ! -z $CRTMPD_PROXY_ENABLE ] && [ $CRTMPD_PROXY_ENABLE -eq 1 ]; then
 fi
 
 askLIVEFLV(){
-	logHeader "LIFE FLV config (required for transcoding)"
+	logSection "LIFE FLV config (required for transcoding)"
 	echo -n "What IP address should crtmpd use to listen to incoming transcoded LIVE FLV connections [$CRTMPD_RTMP_IP] ? "
 	read CRTMPD_LIVEFLV_IP
 	if [ -z $CRTMPD_LIVEFLV_IP ]; then CRTMPD_LIVEFLV_IP=$CRTMPD_RTMP_IP; fi
@@ -104,13 +123,13 @@ askLIVEFLV(){
 	echo "** Are these settings correct ?"
 	echo "- crtmpd LIVE-FVL IP: $CRTMPD_LIVEFLV_IP"
 	echo "- crtmpd LIVE-FLV PORT: $CRTMPD_LIVEFLV_PORT"
-	echo -n "[y/n] "
+	echo -n "[y/N] "
 	read tmp
 	case $tmp in
 		y|Y) echo "* ok";;
 		*) askLIVEFLV;;
 	esac
 }
-if [ $FFMPEG_ENABLE -eq 1 ]; then
-	if [ -z $CRTMPD_LIVEFLV_IP ] || [ -z $CRTMPD_LIVEFLV_PORT ]; then askLIVEFLV; fi
-fi
+#if [ ! -z $FFMPEG_CRTMPD_ENABLE ] && [ $FFMPEG_CRTMPD_ENABLE -eq 1 ]; then
+#	if [ -z $CRTMPD_LIVEFLV_IP ] || [ -z $CRTMPD_LIVEFLV_PORT ]; then askLIVEFLV; fi
+#fi
diff --git a/include/rstream-config/rstream-config-ffmpeg-helper b/include/rstream-config/rstream-config-ffmpeg-helper
--- a/include/rstream-config/rstream-config-ffmpeg-helper
+++ b/include/rstream-config/rstream-config-ffmpeg-helper
@@ -12,13 +12,25 @@
 #
 ######################################################################################
 
-logHeader "* entering FFMPEG config helper"
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ ! -f $FFMPEG_BIN ]; then echo "!! error, ffmpeg not found, exiting !!"; exit 99; fi 
 
 FFMPEG_TRANSCODER_IP=""
 FFMPEG_NGINX_ENABLE=0
 FFMPEG_CRTMPD_ENABLE=0
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+logSection "* entering FFMPEG config helper"
+
+askTranscodingSupport(){
+	echo -n "* Do you want to enable transcoding support [y|N] ? "
+	read tmp
+	case $tmp in
+		y|Y) echo "-! enabling ffmpeg"; FFMPEG_ENABLE=1;;
+		n) echo "-! disabling ffmpeg"; FFMPEG_ENABLE=0;;
+		*) askTranscodingSupport;;
+	esac
+}
+if [ -z $FFMPEG_ENABLE ]; then askTranscodingSupport; fi
 
 askFfmpegIp(){
 	logHeader "General config"
@@ -28,17 +40,33 @@ askFfmpegIp(){
 	if [ -z $FFMPEG_TRANSCODER_IP ] && [ ! -z $CRTMPD_RTMP_IP ]; then FFMPEG_TRANSCODER_IP=$CRTMPD_RTMP_IP; fi
 	if [ -z $FFMPEG_TRANSCODER_IP ] && [ -z $CRTMPD_RTMP_IP ]; then askFfmpegIp; fi
 }
-if [ ! -z $FFMPEG_ENABLE ]; then askFfmpegIp; fi
+if [ ! -z $FFMPEG_ENABLE ] && [ $FFMPEG_ENABLE -eq 1 ]; then askFfmpegIp; fi
 
-askFfmpegNginx(){
-	echo "* Do you want to enable HTTP Live Streaming (HLS) support?"
-	echo -n "[y/n] "
-	read tmp
-	case $tmp in
-		y|Y) echo "-! enabling HLS"; FFMPEG_NGINX_ENABLE=1;;
-		n) echo "-! disabling HLS"; FFMPEG_NGINX_ENABLE=0;;
-		*) askHLSSupport;;
-	esac
+askTranscoderType(){
+#	if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then
+#		echo 
+#		echo -n "** crtmpd is enabled, do you want to transcode *all* streams pushed to \"rtmp://$CRTMPD_RTMP_IP:$CRTMPD_RTMP_PORT/r/<streamname>\" ? [y/N] "
+#		read tmp
+#		case $tmp in
+#			y|Y) echo "-! enabling ffmpeg-transcoding (240p, 360p, 480p, 720p) for crtmpd"; FFMPEG_CRTMPD_ENABLE=1;;
+#			n) echo "-! disabling ffmpeg-transcoding for crtmpd"; FFMPEG_CRTMPD_ENABLE=0;;
+#			*) askTranscoderType;;
+#		esac
+#		if [ ! -z $FFMPEG_CRTMPD_ENABLE ] && [ $FFMPEG_CRTMPD_ENABLE -eq 1 ]; then
+#			if [ -z $CRTMPD_LIVEFLV_IP ] || [ -z $CRTMPD_LIVEFLV_PORT ]; then askLIVEFLV; fi
+#		fi
+#	fi
+
+	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then
+		echo 
+		echo -n "** nginx is enabled, do you want to transcode *all* streams pushed to \"rtmp://$NGINX_RTMP_IP:$NGINX_RTMP_PORT/r/<streamname>\" ? [y/N] "
+		read tmp
+		case $tmp in
+			y|Y) echo "-! enabling ffmpeg-transcoding (240p, 360p, 480p, 720p)  for nginx"; FFMPEG_NGINX_ENABLE=1;;
+			n) echo "-! disabling ffmpeg-transcoding for nginx"; FFMPEG_NGINX_ENABLE=0;;
+			*) askTranscoderType;;
+		esac
+	fi
 }
-if [ ! -z $FFMPEG_NGINX_ENABLE ]; then askFfmpegNginx; fi
+if [ ! -z $FFMPEG_ENABLE ] && [ $FFMPEG_ENABLE -eq 1 ]; then askTranscoderType; fi
 
diff --git a/include/rstream-config/rstream-config-hls-helper b/include/rstream-config/rstream-config-hls-helper
--- a/include/rstream-config/rstream-config-hls-helper
+++ b/include/rstream-config/rstream-config-hls-helper
@@ -13,13 +13,25 @@
 ######################################################################################
 
 if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ ! -f $NGINX_BIN ]; then echo "!! error, nginx not found, exiting !!"; exit 99; fi 
 
-logHeader "* entering HLS config helper"
+logSection "* entering HLS config helper"
 
+HLS_ENABLE=""
 HLS_WWW="$HOME/shared/www"
 HLS_FQDN=""
 HLS_TYPE="nginx"
 HLS_PATH="$HOME/tmp/nginx"
+
+askHLSSupport(){
+	echo -n "* Do you want to enable HTTP Live Streaming (HLS) ezez support ? [y/N]"
+	read tmp
+	case $tmp in
+		y|Y) echo "-! enabling HLS"; HLS_ENABLE=1;;
+		n) echo "-! disabling HLS"; HLS_ENABLE=0;;
+		*) askHLSSupport;;
+	esac
+}
 
 askHLSFQDN(){
 	host=`hostname`
@@ -28,4 +40,7 @@ askHLSFQDN(){
 	if [ -z $tmp ]; then HLS_FQDN="htt://$host/hls/nginx";
 	else HLS_FQDN=$tmp; fi
 }
-if [ ! -z $NGINX_ENABLE ]; then askHLSFQDN; fi
+if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ] && [ -z $HLS_ENABLE ]; then
+	askHLSSupport;
+	askHLSFQDN;
+fi
diff --git a/include/rstream-config/rstream-config-nginx-helper b/include/rstream-config/rstream-config-nginx-helper
--- a/include/rstream-config/rstream-config-nginx-helper
+++ b/include/rstream-config/rstream-config-nginx-helper
@@ -13,8 +13,9 @@
 ######################################################################################
 
 if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ ! -f $NGINX_BIN ]; then echo "!! error, nginx not found, exiting !!"; exit 99; fi 
 
-logHeader "* entering nginx-rtmp config helper"
+logSection "* entering nginx-rtmp config helper"
 
 NGINX_RTMP_FQDN=""
 NGINX_RTMP_IP=""
@@ -24,10 +25,11 @@ NGINX_RTMP_IP=""
 NGINX_RTMP_PORT=""
 NGINX_REGEN_CONF="1"
 
-
 askRTMP(){
 	logHeader "General config"
-	if [ -z $CRTMPD_RTMP_IP ]; then tmp="x.x.x.x"; else tmp=$CRTMPD_RTMP_IP; fi
+	if [ -z $CRTMPD_RTMP_IP ]; then CRTMPD_RTMP_IP=$HOST_IP; fi
+
+	if [ -z $CRTMPD_RTMP_IP ]; then tmp=$HOST_IP; else tmp=$CRTMPD_RTMP_IP; fi
 	echo -n "What IP address should nginx-rtmp use to listen to incoming and outgoing RTMP connections [$tmp] ? "
 	read NGINX_RTMP_IP
 	if [ -z $NGINX_RTMP_IP ] && [ ! -z $CRTMPD_RTMP_IP ]; then NGINX_RTMP_IP=$CRTMPD_RTMP_IP; fi
@@ -37,13 +39,14 @@ askRTMP(){
 	read NGINX_RTMP_PORT
 	if [ -z $NGINX_RTMP_PORT ]; then NGINX_RTMP_PORT=1935; fi
 
+	echo ""
 	echo "** Are these settings correct ?"
 	echo "- nginx-rtmp RTMP IP: $NGINX_RTMP_IP"
 	echo "- nginx-rtmp RTMP PORT: $NGINX_RTMP_PORT"
-	echo -n "[y/n] "
+	echo -n "[y/N] "
 	read tmp
 	case $tmp in
-		y|Y) echo "* ok";;
+		y|Y) ;;
 		*) askRTMP;;
 	esac
 }
