0.5-rc3

diff --git a/bin/rstream b/bin/rstream
--- a/bin/rstream
+++ b/bin/rstream
@@ -47,8 +47,8 @@ clear
 echo ""
 echo ""
 ##
-if [ ! -f $HOME/include/rstream-core ]; then echo "!! invalid rstream setup - invalid HOME ?"; exit 99; fi
-. $HOME/include/rstream-core
+if [ ! -f $HOME/include/core/rstream-core ]; then echo "!! invalid rstream setup - invalid HOME ?"; exit 99; fi
+. $HOME/include/core/rstream-core
 
 ####
 ### Load OS Core files
@@ -59,18 +59,19 @@ case `uname -s` in
 esac
 echo "########## rstream $TAG for $system_os"
 echo ""
-. $HOME/include/rstream-os/rstream-${system_os}_common-helper
+. $HOME/include/${system_os}/rstream-${system_os}_common-helper
 
 rstream-init(){
 	if [ -f $HOME/etc/rstream.conf ]; then
 		. $HOME/etc/rstream.conf
-		. $HOME/include/rstream-os/rstream-${system_os}_crtmpd-helper
-		. $HOME/include/rstream-os/rstream-${system_os}_daemontools-helper
-		. $HOME/include/rstream-os/rstream-${system_os}_nginx-helper
+		. $HOME/include/${system_os}/rstream-${system_os}_crtmpd-helper
+		. $HOME/include/${system_os}/rstream-${system_os}_daemontools-helper
+		. $HOME/include/${system_os}/rstream-${system_os}_nginx-helper
+		. $HOME/include/${system_os}/rstream-${system_os}_ffmpeg-helper
 		rstream-core-init
-		rstream-core-route $1 $2
+		rstream-router $1 $2
 	else
-		. $HOME/include/rstream-config/rstream-config-helper
+		. $HOME/include/core/rstream-config-helper
 		rstream-core-init
 		rstream-config
 		echo ""
diff --git a/bin/rstream-transcoder b/bin/rstream-transcoder
--- a/bin/rstream-transcoder
+++ b/bin/rstream-transcoder
@@ -22,14 +22,17 @@ USER="rstream"
 
 . $HOME/.version
 
+# set DAEMONTOOLS_SERVICE based on default port service path
+DAEMONTOOLS_SERVICE="/var/service"
+
 ####
 ### Load OS Core files
 ####
 echo ""
 echo ""
 ##
-if [ ! -f $HOME/include/rstream-core ]; then echo "!! invalid rstream setup - invalid HOME ?"; exit 99; fi
-. $HOME/include/rstream-core
+if [ ! -f $HOME/include/core/rstream-core ]; then echo "!! invalid rstream setup - invalid HOME ?"; exit 99; fi
+. $HOME/include/core/rstream-core
 
 ####
 ### Load OS Core files
@@ -40,11 +43,12 @@ case `uname -s` in
 esac
 echo "########## rstream-transcoder-$TAG for rstream $TAG on $system_os"
 echo ""
-. $HOME/include/rstream-os/rstream-${system_os}_common-helper
-#. $HOME/bin/rstream-${system_os}_nginx-helper
-#. $HOME/bin/rstream-${system_os}_crtmpd-helper
-#. $HOME/bin/rstream-${system_os}_daemontools-helper
+. $HOME/include/${system_os}/rstream-${system_os}_common-helper
 . $HOME/etc/rstream.conf
+. $HOME/include/${system_os}/rstream-${system_os}_crtmpd-helper
+. $HOME/include/${system_os}/rstream-${system_os}_daemontools-helper
+. $HOME/include/${system_os}/rstream-${system_os}_nginx-helper
+. $HOME/include/${system_os}/rstream-${system_os}_ffmpeg-helper
 rstream-core-init
 
 
@@ -73,28 +77,6 @@ transcoderNginx(){
 	dest_app="r"
 	if [ -z $1 ]; then echo "!! error missing stream name, exiting !!"; exit 99; fi
 	stream=$1
-
-	if [ ! -z $2 ] && [ $2 = "-link" ]; then
-		echo "*+ generating new ffmpeg/run script";
-		checkDir $HOME/tmp/ffmpeg -c rstream 700
-		checkDir $HOME/var/log/ffmpeg -c rstream 700
-		checkDir $HOME/var/supervise/ffmpeg-nginx-${stream}/log -c rstream 755
-		cat $HOME/include/templates/ffmpeg-run.tpl \
-			| sed s,_HOME_,$HOME,g \
-			| sed s,_USER_,$USER,g \
-			| sed s,_STREAM_,$stream,g \
-			| sed s,_DAEMON_,'nginx',g \
-			> $HOME/var/supervise/ffmpeg-nginx-${stream}/run
-			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/run
-		echo "*+ generating new ffmpeg/run/log script";
-		cat $HOME/include/templates/ffmpeg-run-log.tpl \
-			| sed s,_HOME_,$HOME,g \
-			| sed s,_USER_,$USER,g \
-			> $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
-			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
-			exit 0;
-	fi
-
 
 	src="rtmp://$NGINX_RTMP_IP:$NGINX_RTMP_PORT/$app/$stream"
 	transcodeInit "rtmp" $NGINX_RTMP_IP $NGINX_RTMP_PORT $dest_app $stream
@@ -135,26 +117,26 @@ transcoderCrtmpd(){
 	stream=$1
 
 
-	if [ ! -z $2 ] && [ $2 = "-i" ]; then
-		echo "*+ generating new ffmpeg/run script";
-		checkDir $HOME/tmp/ffmpeg -c rstream 700
-		checkDir $HOME/var/log/ffmpeg -c rstream 700
-		checkDir $HOME/var/supervise/ffmpeg-nginx-${stream}/log -c rstream 755
-		cat $HOME/include/templates/ffmpeg-run.tpl \
-			| sed s,_HOME_,$HOME,g \
-			| sed s,_USER_,$USER,g \
-			| sed s,_STREAM_,$stream,g \
-			| sed s,_DAEMON_,'nginx',g \
-			> $HOME/var/supervise/ffmpeg-nginx-${stream}/run
-			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/run
-		echo "*+ generating new ffmpeg/run/log script";
-		cat $HOME/include/templates/ffmpeg-run-log.tpl \
-			| sed s,_HOME_,$HOME,g \
-			| sed s,_USER_,$USER,g \
-			> $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
-			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
-			exit 0;
-	fi
+#	if [ ! -z $2 ] && [ $2 = "-i" ]; then
+#		echo "*+ generating new ffmpeg/run script";
+#		checkDir $HOME/tmp/ffmpeg -c rstream 700
+#		checkDir $HOME/var/log/ffmpeg -c rstream 700
+#		checkDir $HOME/var/supervise/ffmpeg-nginx-${stream}/log -c rstream 755
+#		cat $HOME/include/templates/ffmpeg-run.tpl \
+#			| sed s,_HOME_,$HOME,g \
+#			| sed s,_USER_,$USER,g \
+#			| sed s,_STREAM_,$stream,g \
+#			| sed s,_DAEMON_,'nginx',g \
+#			> $HOME/var/supervise/ffmpeg-nginx-${stream}/run
+#			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/run
+#		echo "*+ generating new ffmpeg/run/log script";
+#		cat $HOME/include/templates/ffmpeg-run-log.tpl \
+#			| sed s,_HOME_,$HOME,g \
+#			| sed s,_USER_,$USER,g \
+#			> $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
+#			chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
+#			exit 0;
+#	fi
 
 	src="rtmp://$CRTMPD_RTMP_IP:$CRTMPD_RTMP_PORT/$app/$stream"
 
@@ -222,16 +204,21 @@ routeTranscoder(){
 		-run)
 			if [ -z $2 ]; then routeHelp; exit 99; fi
 			case $2 in
-				crtmpd) transcoderCrtmpd $3 $4;; # CRTMPD (RTMP / FLV) > ffmpeg > CRTMPD (tcvp / FLV)
-				nginx) transcoderNginx $3 $4;; # CRTMPD (RTMP / FLV) > ffmpeg > NGINX (rtmp / FLV)
+				crtmpd) transcoderCrtmpd $3;; # CRTMPD (RTMP / FLV) > ffmpeg > CRTMPD (tcvp / FLV)
+				nginx) transcoderNginx $3;; # CRTMPD (RTMP / FLV) > ffmpeg > NGINX (rtmp / FLV)
 				*) routeHelp;;
 			esac
 		;;
+		-service-create) ffmpeg-router "create" $3;;
+		-service-link) ffmpeg-router "link" $3;;
 	esac
 }
 
 
 routeTranscoder $1 $2 $3 $4
+
+#### Below lies the graveyard of my ffmpeg tests..
+
 #checkDir $HLS_PATH/$app/$stream -rc
 
 # From https://groups.google.com/forum/#!topic/c-rtmp-server/bzsV61wJGHg[1-25]
diff --git a/include/core/rstream-config-crtmpd-helper b/include/core/rstream-config-crtmpd-helper
--- a/include/core/rstream-config-crtmpd-helper
+++ b/include/core/rstream-config-crtmpd-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 if [ ! -f $CRTMPD_BIN ]; then echo "!! error, crtmpd not found, exiting !!"; exit 99; fi 
 
 logSection "* entering crtmpd config helper"
@@ -61,7 +61,7 @@ askProxyData(){
 
 	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then rtmp_host="rtmp://$CRTMPD_RTMP_IP:1935/proxy"
 	else rtmp_host="rtmp://user:pass@host:port/app"; fi
-	echo -n "To what rtmp address should we push the current stream to [$rtmp_host] ? "
+	echo -n "To what rtmp address should we push the current stream to (do not include the streamName in the url!) ? [$rtmp_host] "
 	read CRTMPD_PROXY_URL
 	if [ -z $CRTMPD_PROXY_URL ]; then CRTMPD_PROXY_URL=$rtmp_host; fi
 
@@ -73,7 +73,9 @@ askProxyData(){
 		*) askProxyData;;
 	esac
 
-	if [ -z $CRTMPD_PROXY_TRANSPARENT ] || [ ! $CRTMPD_PROXY_TRANSPARENT -eq 1 ]; then
+	if [ ! -z $CRTMPD_PROXY_TRANSPARENT ] && [ $CRTMPD_PROXY_TRANSPARENT -eq 1 ]; then
+		echo "** Skipping localStreamName and targetStreamName (CRTMPD_PROXY_TRANSPARENT is set to true)"
+	else
 		echo -n "What local stream should we push to $CRTMPD_PROXY_URL [test] ? "
 		read CRTMPD_PROXY_LSTREAM
 		if [ -z $CRTMPD_PROXY_LSTREAM ]; then CRTMPD_PROXY_LSTREAM="test"; fi
diff --git a/include/core/rstream-config-ffmpeg-helper b/include/core/rstream-config-ffmpeg-helper
--- a/include/core/rstream-config-ffmpeg-helper
+++ b/include/core/rstream-config-ffmpeg-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 if [ ! -f $FFMPEG_BIN ]; then echo "!! error, ffmpeg not found, exiting !!"; exit 99; fi 
 
 FFMPEG_TRANSCODER_IP=""
diff --git a/include/core/rstream-config-helper b/include/core/rstream-config-helper
--- a/include/core/rstream-config-helper
+++ b/include/core/rstream-config-helper
@@ -12,13 +12,13 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 
 RSTREAM_TYPE=""
+CRTMPD_ENABLE=""
+NGINX_ENABLE=""
 FFMPEG_ENABLE=""
 HLS_ENABLE=""
-FFMPEG_NGINX_TRANSCODING=""
-FFMPEG_CRTMPD_TRANSCODING=""
 
 ####
 ### Start the installer logic
@@ -50,16 +50,15 @@ rstream-config(){
 
 	if [ -z $CRTMPD_ENABLE ] && [ -z $NGINX_ENABLE ]; then askServers; fi
 
-	if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then . $HOME/include/rstream-config/rstream-config-crtmpd-helper;fi
-	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then . $HOME/include/rstream-config/rstream-config-nginx-helper;fi
+	if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then . $HOME/include/core/rstream-config-crtmpd-helper;fi
+	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then . $HOME/include/core/rstream-config-nginx-helper;fi
 	# hls only works with nginx for now.
-	. $HOME/include/rstream-config/rstream-config-hls-helper
-	. $HOME/include/rstream-config/rstream-config-ffmpeg-helper
+	. $HOME/include/core/rstream-config-hls-helper
+	. $HOME/include/core/rstream-config-ffmpeg-helper
 
 
 	genConf	
 }
-
 
 genConf(){
 	backupFile $CONFIG_FILE
diff --git a/include/core/rstream-config-hls-helper b/include/core/rstream-config-hls-helper
--- a/include/core/rstream-config-hls-helper
+++ b/include/core/rstream-config-hls-helper
@@ -12,17 +12,15 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 if [ ! -f $NGINX_BIN ]; then echo "!! error, nginx not found, exiting !!"; exit 99; fi 
 
 logSection "* entering HLS config helper"
 
-HLS_ENABLE=""
 HLS_WWW="$HOME/shared/www"
 HLS_FQDN=""
 HLS_TYPE="nginx"
 HLS_PATH="$HOME/tmp/nginx"
-
 askHLSSupport(){
 	echo -n "* Do you want to enable HTTP Live Streaming (HLS) ezez support ? [y/N]"
 	read tmp
@@ -39,7 +37,9 @@ askHLSFQDN(){
 	if [ -z $tmp ]; then HLS_FQDN="htt://$host/hls/nginx";
 	else HLS_FQDN=$tmp; fi
 }
-if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ] && [ -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ]; then
+if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then
 	askHLSSupport;
-	askHLSFQDN;
+#	askHLSFQDN;
+else
+	echo "-! Skipping HLS configuration (not supported without nginx)"
 fi
diff --git a/include/core/rstream-config-nginx-helper b/include/core/rstream-config-nginx-helper
--- a/include/core/rstream-config-nginx-helper
+++ b/include/core/rstream-config-nginx-helper
@@ -11,7 +11,7 @@
 # - https://github.com/kelexel/rstream
 #
 ######################################################################################
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 if [ ! -f $NGINX_BIN ]; then echo "!! error, nginx not found, exiting !!"; exit 99; fi 
 
 logSection "* entering nginx-rtmp config helper"
@@ -19,7 +19,6 @@ logSection "* entering nginx-rtmp config helper"
 NGINX_RTMP_FQDN=""
 NGINX_RTMP_IP=""
 NGINX_RTMP_PORT=""
-
 NGINX_RTMP_IP=""
 NGINX_RTMP_PORT=""
 NGINX_REGEN_CONF="1"
diff --git a/include/core/rstream-core b/include/core/rstream-core
--- a/include/core/rstream-core
+++ b/include/core/rstream-core
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routeHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 
 ## Used for log consmetics
 logRoute(){
@@ -80,12 +80,14 @@ debugReset(){
 	cmd="$cmd && rm -f $HOME/etc/nginx*"
 	cmd="$cmd && rm -f $HOME/etc/crtmpd*"
 	cmd="$cmd && rm -f $DAEMONTOOLS_SERVICE/crtmpd"
-	echo "-! Are you sure you want to execute:"
+	cmd="$cmd && rm -f $DAEMONTOOLS_SERVICE/nginx"
+	cmd="$cmd && rm -f $DAEMONTOOLS_SERVICE/ffmpeg-*"
+	echo -n "-! Are you sure you want to execute: [y/N] "
 	echo $cmd;
-	echo "[y/N]"
+	echo -n "[y/N] "
 	read debug_confirmation
 	case $debug_confirmation in
-		[yY]) rstream-core-route "stop"; echo ""; echo "* Cleaning up.." `$cmd`;;
+		[yY]) rstream-router "stop"; echo ""; echo "* Cleaning up.." `$cmd`;;
 		*) echo "!! User-canceled reset" exit 1;;
 	esac
 }
@@ -108,13 +110,13 @@ rstream-core-init(){
 	checkDir $HOME/tmp -c
 }
 
-rstream-core-route(){
+rstream-router(){
 	# check for config file
-	checkFile $HOME/etc/rstream.conf 1
+	#checkFile $HOME/etc/rstream.conf 1
 	if [ -z $1 ]; then routeHelp; exit 1; fi
 	case $1 in
 		stop)
-			daemontoolsRouter "stop"
+			daemontools-router "stop"
 			killall -u $USER
 			killall -TERM readproctitle supervise multilog crtmpserver
 		;;
@@ -122,29 +124,29 @@ rstream-core-route(){
 			checkServiceEnabled crtmpd -nn
 			checkServiceEnabled nginx -nn
 			checkServiceEnabled svscan -y
-			daemontoolsRouter "start"
-			rstream-core-route "status"
+			daemontools-router "start"
+			rstream-router "status"
 		;;
 		restart)
-			rstream-core-route "stop"
-			rstream-core-route "start"
+			rstream-router "stop"
+			rstream-router "start"
 		;;
 		stat|status)
-			daemontoolsRouter "status";
-			if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then crtmpdRouter "status"; fi
-			if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then nginxRouter "status"; fi
+			daemontools-router "status";
+			if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then crtmpd-router "status"; fi
+			if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then nginx-router "status"; fi
 		;;
 		-link) setupServices;;
 		-crtmp|-crtmpd)
 			if [ -z $2 ]; then route; exit 99; fi
-			crtmpdRouter $2
+			crtmpd-router $2
 		;;
 		-nginx)
 			if [ -z $2 ]; then route; exit 99; fi
-			nginxRouter $2
+			nginx-router $2
 		;;
 		-daemontools|svscan)
-			daemontoolsRouter $2
+			daemontools-router $2
 		;;
 		-debug-cycle) debugCycle;;
 		-debug-reset) debugReset;;
@@ -160,13 +162,13 @@ rstream-core-route(){
 			if [ ! -f $HOME/etc/rstream.conf ]; then
 				rstream-config
 			else
-#				rstream-core-route "stop"
+#				rstream-router "stop"
 				if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then
-					crtmpdRouter "setup"
+					crtmpd-router "setup"
 				fi
 				if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then
-					nginxRouter "setup"
-					daemontoolsRouter "setup"
+					nginx-router "setup"
+					daemontools-router "setup"
 				fi
 			fi
 		;;
diff --git a/include/freebsd9/rstream-freebsd9_common-helper b/include/freebsd9/rstream-freebsd9_common-helper
--- a/include/freebsd9/rstream-freebsd9_common-helper
+++ b/include/freebsd9/rstream-freebsd9_common-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 
 ## Used to check the existence of a given username on the system
 checkUser(){
diff --git a/include/freebsd9/rstream-freebsd9_crtmpd-helper b/include/freebsd9/rstream-freebsd9_crtmpd-helper
--- a/include/freebsd9/rstream-freebsd9_crtmpd-helper
+++ b/include/freebsd9/rstream-freebsd9_crtmpd-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 
 ####
 ### CRTMPD setup
@@ -103,7 +103,7 @@ crtmpdSetup(){
 ####
 ### CRTMPD router
 ####
-crtmpdRouter(){
+crtmpd-router(){
 	if [ -z $1 ]; then routeHelp; exit 1; fi
 	logRoute "crtmpd" $1 
 	if [ -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 0 ]; then return; fi
@@ -122,7 +122,7 @@ crtmpdRouter(){
 			echo "* stopping crtmpd service"
 			svc -d $DAEMONTOOLS_SERVICE/crtmpd
 			svc -d $DAEMONTOOLS_SERVICE/crtmpd/log
-			crtmpdRouter "status"
+			crtmpd-router "status"
 		;;
 		start)
 			echo "* starting crtmpd service"
@@ -130,11 +130,11 @@ crtmpdRouter(){
 			svc -u $DAEMONTOOLS_SERVICE/crtmpd/log
 			echo "* waiting 5seconds ..."
 			sleep 5
-			crtmpdRouter "status"
+			crtmpd-router "status"
 		;;
 		restart)
-			crtmpdRouter "stop"
-			crtmpdRouter "start"
+			crtmpd-router "stop"
+			crtmpd-router "start"
 		;;
 		test)
 			echo "* testing crtmpd, hit ctrl+c to abort"
diff --git a/include/freebsd9/rstream-freebsd9_daemontools-helper b/include/freebsd9/rstream-freebsd9_daemontools-helper
--- a/include/freebsd9/rstream-freebsd9_daemontools-helper
+++ b/include/freebsd9/rstream-freebsd9_daemontools-helper
@@ -12,7 +12,7 @@
 #
 ######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 
 ####
 ### daemontools Setup
@@ -44,7 +44,7 @@ daemontoolsLinkServices(){
 ####
 ### daemontools Router
 ####
-daemontoolsRouter(){
+daemontools-router(){
 	if [ -z $1 ]; then routeHelp; exit 1; fi
 	logRoute "daemontools" $1 
 	case $1 in
@@ -62,11 +62,12 @@ daemontoolsRouter(){
 		start)
 			echo "* starting svscan"
 			service svscan start
-			daemontoolsRouter "status"
+			echo "** Sleeping 5 seconds..."
+			sleep 5
 		;;
 		restart)
-			daemontoolsRouter "stop"
-			daemontoolsRouter "start"
+			daemontools-router "stop"
+			daemontools-router "start"
 		;;
 		*) routeHelp;;
 	esac
diff --git a/include/freebsd9/rstream-freebsd9_nginx-helper b/include/freebsd9/rstream-freebsd9_nginx-helper
--- a/include/freebsd9/rstream-freebsd9_nginx-helper
+++ b/include/freebsd9/rstream-freebsd9_nginx-helper
@@ -12,7 +12,7 @@
 #
 #######################################################################################
 
-if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
+if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi
 
 ####
 ### Nginx setup
@@ -29,7 +29,7 @@ nginxSetup(){
 	if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ] && [ ! `$nginx_bin -V 2>&1 | grep -q hls;  echo $?` -eq 0 ]; then echo "!! nginx was not compiled with nginx-rtmp/hls support , existing."; exit 99; 
 		else if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ]; then echo "* found nginx-rtmp/hls support"; fi
 	fi
-	checkDir $HOME/var/log/nginx -c
+	checkDir $HOME/var/log/nginx -c www 755
 	checkDir $HOME/shared/www/stats -c www 777
 	#checkDir $HOME/var/log/nginx-crtmpd-ffmpeg -c $USER
 
@@ -51,13 +51,12 @@ nginxSetup(){
 			| sed s,_NGINX_RTMP_STREAM_,$NGINX_RTMP_STREAM,g \
 			> $NGINX_CONF
 	fi
+	
+	# copy mime types
+	cp $HOME/include/templates/nginx-rtmp-mime-types.tpl $HOME/etc/nginx-rtmp-mime.types
 
 	# only make the following tests if NGINX_HLS is set to 1
 	if [ $HLS_ENABLE ]; then
-		# set nginx_mime_types to default FreeBSD nginx port config location
-		nginx_mime_types="/usr/local/etc/nginx/mime.types"
-		# copy mime types
-		cp $HOME/include/templates/nginx-rtmp-mime-types.tpl $HOME/etc/nginx-rtmp-mime.types
 
 		echo "*+ enabling HLS in nginx configuration"
 		cat $NGINX_CONF \
@@ -94,7 +93,7 @@ nginxSetup(){
 	# generate nginx/log/run script
 	echo "*+ generating new nginx/log/run script";
 	cat $HOME/include/templates/nginx-run-log.tpl \
-		| sed s,_USER_,'nobody',g \
+		| sed s,_USER_,'www',g \
 		| sed s,_LOG_DIR_,$HOME/var/log/nginx,g \
 		> $HOME/var/supervise/nginx/log/run
 		chmod 755 $HOME/var/supervise/nginx/log/run
@@ -102,7 +101,7 @@ nginxSetup(){
 ####
 ### CRTMPD router
 ####
-nginxRouter(){
+nginx-router(){
 	if [ -z $1 ]; then routeHelp; exit 1; fi
 	logRoute "nginx" $1 
 	if [ -z $NGINX_ENABLE ] || [ ! $NGINX_ENABLE -eq 1 ]; then break; fi
@@ -114,21 +113,24 @@ nginxRouter(){
 		status|stat)
 			echo "* checking if nginx is running"
 			svstat $DAEMONTOOLS_SERVICE/nginx
+			svstat $DAEMONTOOLS_SERVICE/nginx/log
 		;;
 		stop)
 			echo "* stopping nginx"
 			svc -d $DAEMONTOOLS_SERVICE/nginx
-			if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ]; then nginxRouter "hls-flush"; fi
+			svc -d $DAEMONTOOLS_SERVICE/nginx/log
+			if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ]; then nginx-router "hls-flush"; fi
 		;;
 		start)
 			echo "* starting nginx"
 			svc -u $DAEMONTOOLS_SERVICE/nginx
+			svc -u $DAEMONTOOLS_SERVICE/nginx/log
 			sleep 5
-			nginxRouter "status"
+			nginx-router "status"
 		;;
 		restart)
-			nginxRouter "stop"
-			nginxRouter "start"
+			nginx-router "stop"
+			nginx-router "start"
 		;;
 		hls-flush)
 			echo "* flushing hls directory"
