push 0.3t

diff --git a/bin/rstream-transcoder b/bin/rstream-transcoder
--- a/bin/rstream-transcoder
+++ b/bin/rstream-transcoder
@@ -20,7 +20,7 @@ HOME="/home/rstream"
 # This only checks & creates the default user test on your system
 USER="rstream"
 
-TAG="0.3"
+. $HOME/.version
 
 ####
 ### Load OS Core files
@@ -65,17 +65,20 @@ transcodeInit(){
 	dest_480="$proto://${dest_host}:${dest_port}/480p/$stream"
 	dest_360="$proto://${dest_host}:${dest_port}/360p/$stream"
 	dest_240="$proto://${dest_host}:${dest_port}/240p/$stream"
+
+	ffmpeg_bin="/usr/local/bin/ffmpeg"
 }
 
 transcoderMethod1(){
-	if [ -z $FFMPEG_CRTMPD_TRANSCODING ] || [ ! $FFMPEG_CRTMPD_TRANSCODING -eq 1 ]; then echo "Error: \"-run m1\" supplied, but FFMPEG_CRTMPD_TRANSCODING is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
+	if [ -z $FFMPEG_CRTMPD_TO_CRTMPD_TRANSCODING ] || [ ! $FFMPEG_CRTMPD_TO_CRTMPD_TRANSCODING -eq 1 ]; then echo "Error: \"-run m1\" supplied, but FFMPEG_CRTMPD_TO_CRTMPD_TRANSCODING is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
 	transcodeInit "tcp" $CRTMPD_LIVEFLV_IP $CRTMPD_LIVEFLV_PORT $NGINX_RTMP_STREAM
 
 	stream=$NGINX_RTMP_STREAM
+	# hls_iphone="$HOME/etc/ffmpeg-presets/libx264-ipod320.ffpreset"
+	# hls_ipad="$HOME/etc/ffmpeg-presets/libx264-ipod640.ffpreset"
 	hls_iphone="libx264-ipod320"
 	hls_ipad="libx264-ipod640"
 
-	ffmpeg_bin="/usr/local/bin/ffmpeg"
 	#ffmpeg_bin=/home/rstream/bin/ffmpeg
 	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 500k -f flv -metadata streamName=${stream} -f flv $dest_720"
 	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 854x480 -b:v 500k -f flv -metadata streamName=${stream} -f flv $dest_480"
@@ -85,7 +88,36 @@ transcoderMethod1(){
 		checkDir $HOME/tmp/hls/ipad/$stream -c www 777
 		checkDir $HOME/tmp/hls/iphone/$stream -c www 777
 		checkDir "$hls_dest/$app/iphone" -rc
-		cmd=" -re -an -c:v libx264 -b:v 128k -vpre $hls_iphonet -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $hls_dest/$app/$stream/${stream}_iphone.m3u8 -segment_format mpegts $hls_dest/$app/iphone/stream%05d.ts"
+		cmd=" -re -an -c:v libx264 -b:v 128k -vpre $hls_iphone -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $hls_dest/$app/$stream/${stream}_iphone.m3u8 -segment_format mpegts $hls_dest/$app/iphone/stream%05d.ts"
+		checkDir "$hls_dest/$app/ipad" -rc
+		cmd=" -re -an -c:v libx264 -b:v 256k -vpre $hls_ipad -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $hls_dest/$app/$stream/${stream}_ipad.m3u8 -segment_format mpegts $hls_dest/ipad/$stream/stream%05d.ts"
+	fi
+	echo ""
+	logHeader "Running $cmd"
+	echo
+	exec $ffmpeg_bin -threads 15 -i "$src live=1" $cmd
+}
+
+transcoderMethod2(){
+	if [ -z $FFMPEG_CRTMPD_TO_NGINX_TRANSCODING ] || [ ! $FFMPEG_CRTMPD_TO_NGINX_TRANSCODING -eq 1 ]; then echo "Error: \"-run m2\" supplied, but FFMPEG_CRTMPD_TO_NGINX_TRANSCODING is not set to \"1\" in $HOME/etc/rstream.conf, exiting !"; exit 98; fi
+	transcodeInit "rtmp" $NGINX_RTMP_IP $NGINX_RTMP_PORT $NGINX_RTMP_STREAM
+
+	stream=$NGINX_RTMP_STREAM
+	# hls_iphone="$HOME/etc/ffmpeg-presets/libx264-ipod320.ffpreset"
+	# hls_ipad="$HOME/etc/ffmpeg-presets/libx264-ipod640.ffpreset"
+	hls_iphone="libx264-ipod320"
+	hls_ipad="libx264-ipod640"
+
+	#ffmpeg_bin=/home/rstream/bin/ffmpeg
+	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 1280x720 -b:v 500k -f flv -f flv $dest_720"
+	cmd="$cmd -re -acodec libfaac -ar 44100 -b:a 96k -vcodec libx264 -s 854x480 -b:v 500k -f flv -f flv $dest_480"
+	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 96k -vcodec libx264 -s 640x360 -b:v 300k -f flv -f flv $dest_360"
+	cmd="$cmd -re -acodec libfaac -ar 22050 -b:a 48k -vcodec libx264 -s 426x250 -b:v 100k -f flv -f flv $dest_240"
+	if [ ! -z $FFMPEG_HLS ] && [ $FFMPEG_HLS -eq 1 ]; then
+		checkDir $HOME/tmp/hls/ipad/$stream -c www 777
+		checkDir $HOME/tmp/hls/iphone/$stream -c www 777
+		checkDir "$hls_dest/$app/iphone" -rc
+		cmd=" -re -an -c:v libx264 -b:v 128k -vpre $hls_iphone -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $hls_dest/$app/$stream/${stream}_iphone.m3u8 -segment_format mpegts $hls_dest/$app/iphone/stream%05d.ts"
 		checkDir "$hls_dest/$app/ipad" -rc
 		cmd=" -re -an -c:v libx264 -b:v 256k -vpre $hls_ipad -flags -global_header -map 0 -f segment -segment_time 4 -segment_list $hls_dest/$app/$stream/${stream}_ipad.m3u8 -segment_format mpegts $hls_dest/ipad/$stream/stream%05d.ts"
 	fi
@@ -102,7 +134,8 @@ routeTranscoder(){
 		-run)
 			if [ -z $2 ]; then routeHelp; exit 99; fi
 			case $2 in
-				m1) transcoderMethod1;;
+				m1) transcoderMethod1;; # CRTMPD (RTMP / FLV) > ffmpeg > CRTMPD (tcvp / FLV)
+				m2) transcoderMethod2;; # CRTMPD (RTMP / FLV) > ffmpeg > NGINX (rtmp / FLV)
 				*) routeHelp;;
 			esac
 		;;
